#!/usr/bin/bash

################################################################################
# Utility to login to all of the damn FedEx servers that need to be managed.
# 
# usage: $0 system level target
# example: $0 wgrt 3 cos1
################################################################################

# setup username(s)
username="ts796565"
firewall_username="f796565"
firewall_host="sagcfedcwl01.inf.fedex.com"

# setup a systems array
declare -A SYSTEMS

# SWS APP
SYSTEMS["sws 1 1"]="$username@uje31006.freight.fedex.com"
SYSTEMS["sws 2 1"]="$username@ije31060.freight.fedex.com"
SYSTEMS["sws 3 1"]="$username@sje31118.freight.fedex.com"
SYSTEMS["sws 3 2"]="$username@sje31119.freight.fedex.com"
SYSTEMS["sws 4 1"]="$username@vje31135.freight.fedex.com"
SYSTEMS["sws 4 2"]="$username@vje31136.freight.fedex.com"
SYSTEMS["sws 5 1"]="$username@eje31036.freight.fedex.com"
SYSTEMS["sws 5 2"]="$username@eje31037.freight.fedex.com"
SYSTEMS["sws 6 1"]="$username@qje31025.freight.fedex.com"
SYSTEMS["sws 6 2"]="$username@qje31026.freight.fedex.com"
SYSTEMS["sws 7 1"]="$username@pje31109.freight.fedex.com"
SYSTEMS["sws 7 2"]="$username@pje31110.freight.fedex.com"
SYSTEMS["fxfsws 1 1"]="$username@uje31094.freight.fedex.com"
SYSTEMS["fxfsws 2 1"]="$username@ije31103.freight.fedex.com"
SYSTEMS["fxfsws 3 1"]="$username@sje31322.freight.fedex.com"
SYSTEMS["fxfsws 3 2"]="$username@sje31323.freight.fedex.com"
SYSTEMS["fxfsws 4 1"]="$username@vje31328.freight.fedex.com"
SYSTEMS["fxfsws 4 2"]="$username@vje31329.freight.fedex.com"
SYSTEMS["fxfsws 7 1"]="-J $firewall_username@$firewall_host $username@pje31350.freight.fedex.com"
SYSTEMS["fxfsws 7 2"]="-J $firewall_username@$firewall_host $username@pje31351.freight.fedex.com"

# WDPA SYSTEMS
SYSTEMS["wdpa 1 1"]="$username@wdpawebbase1.idev.fedex.com"
SYSTEMS["wdpa 1 S1"]="$username@wdpawebsbox1.idev.fedex.com"
SYSTEMS["wdpa 2 1"]="$username@wdpawebdev1.idev.fedex.com"
SYSTEMS["wdpa 2 2"]="$username@wdpawebdev2.idev.fedex.com"
SYSTEMS["wdpa 3 cos1"]="$username@wdpawebdrt-cos1.idev.fedex.com"
SYSTEMS["wdpa 3 cos2"]="$username@wdpawebdrt-cos2.idev.fedex.com"
SYSTEMS["wdpa 3 wtc1"]="$username@wdpawebdrt-wap1.idev.fedex.com"
SYSTEMS["wdpa 3 wtc2"]="$username@wdpawebdrt-wap2.idev.fedex.com"
SYSTEMS["wdpa 4 cos1"]="$username@wdpawebstress-cos1.idev.fedex.com"
SYSTEMS["wdpa 4 cos2"]="$username@wdpawebstress-cos2.idev.fedex.com"
SYSTEMS["wdpa 4 west1"]="$username@wdpawebstress-wap1.zmd.idev.fedex.com"
SYSTEMS["wdpa 4 west2"]="$username@wdpawebstress-wap2.zmd.idev.fedex.com"
SYSTEMS["wdpa 5 1"]="$username@wdpawebbit1.idev.fedex.com"
SYSTEMS["wdpa 5 2"]="$username@wdpawebbit2.idev.fedex.com"
SYSTEMS["wdpa 7 cos1"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos1.zmd.fedex.com"
SYSTEMS["wdpa 7 cos2"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos2.zmd.fedex.com"
SYSTEMS["wdpa 7 cos3"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos3.zmd.fedex.com"
SYSTEMS["wdpa 7 cos4"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos4.zmd.fedex.com"
SYSTEMS["wdpa 7 cos5"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos5.zmd.fedex.com"
SYSTEMS["wdpa 7 cos6"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos6.zmd.fedex.com"
SYSTEMS["wdpa 7 cos7"]="-J $firewall_username@$firewall_host $username@wdpaweb-cos7.zmd.fedex.com"
SYSTEMS["wdpa 7 wap1"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap1.zmd.fedex.com"
SYSTEMS["wdpa 7 wap2"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap2.zmd.fedex.com"
SYSTEMS["wdpa 7 wap3"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap3.zmd.fedex.com"
SYSTEMS["wdpa 7 wap4"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap4.zmd.fedex.com"
SYSTEMS["wdpa 7 wap5"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap5.zmd.fedex.com"
SYSTEMS["wdpa 7 wap6"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap6.zmd.fedex.com"
SYSTEMS["wdpa 7 wap7"]="-J $firewall_username@$firewall_host $username@wdpaweb-wap7.zmd.fedex.com"

# WGRT SYSTEMS
SYSTEMS["wgrt 1 1"]="$username@wgrtwebbase1.idev.fedex.com"
SYSTEMS["wgrt 1 S1"]="$username@wgrtwebsbox1.idev.fedex.com"
SYSTEMS["wgrt 2 1"]="$username@wgrtwebdev1.idev.fedex.com"
SYSTEMS["wgrt 2 2"]="$username@wgrtwebdev2.idev.fedex.com"
SYSTEMS["wgrt 3 cos1"]="$username@wgrtwebdrt-cos1.idev.fedex.com"
SYSTEMS["wgrt 3 cos2"]="$username@wgrtwebdrt-cos2.idev.fedex.com"
SYSTEMS["wgrt 3 wtc1"]="$username@wgrtwebdrt-wap1.idev.fedex.com"
SYSTEMS["wgrt 3 wtc2"]="$username@wgrtwebdrt-wap2.idev.fedex.com"
SYSTEMS["wgrt 4 cos1"]="$username@wgrtwebstress-cos1.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 cos2"]="$username@wgrtwebstress-cos2.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 cos3"]="$username@wgrtwebstress-cos3.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 cos4"]="$username@wgrtwebstress-cos4.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 cos5"]="$username@wgrtwebstress-cos5.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 west1"]="$username@wgrtwebstress-wap1.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 west2"]="$username@wgrtwebstress-wap2.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 west3"]="$username@wgrtwebstress-wap3.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 west4"]="$username@wgrtwebstress-wap4.zmd.idev.fedex.com"
SYSTEMS["wgrt 4 west5"]="$username@wgrtwebstress-wap5.zmd.idev.fedex.com"
SYSTEMS["wgrt 5 1"]="$username@wgrtwebbit1.idev.fedex.com"
SYSTEMS["wgrt 5 2"]="$username@wgrtwebbit2.idev.fedex.com"
SYSTEMS["wgrt 6 cos1"]="-J $firewall_username@$firewall_host $username@wgrtwebtest-cos1.zmd.fedex.com"
SYSTEMS["wgrt 6 cos2"]="-J $firewall_username@$firewall_host $username@wgrtwebtest-cos2.zmd.fedex.com"
SYSTEMS["wgrt 6 wap1"]="-J $firewall_username@$firewall_host $username@wgrtwebtest-wap1.zmd.fedex.com"
SYSTEMS["wgrt 6 wap2"]="-J $firewall_username@$firewall_host $username@wgrtwebtest-wap2.zmd.fedex.com"
SYSTEMS["wgrt 7 cos1"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos1.zmd.fedex.com"
SYSTEMS["wgrt 7 cos2"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos2.zmd.fedex.com"
SYSTEMS["wgrt 7 cos3"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos3.zmd.fedex.com"
SYSTEMS["wgrt 7 cos4"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos4.zmd.fedex.com"
SYSTEMS["wgrt 7 cos5"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos5.zmd.fedex.com"
SYSTEMS["wgrt 7 cos6"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos6.zmd.fedex.com"
SYSTEMS["wgrt 7 cos7"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos7.zmd.fedex.com"
SYSTEMS["wgrt 7 cos8"]="-J $firewall_username@$firewall_host $username@wgrtweb-cos8.zmd.fedex.com"
SYSTEMS["wgrt 7 wap1"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap1.zmd.fedex.com"
SYSTEMS["wgrt 7 wap2"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap2.zmd.fedex.com"
SYSTEMS["wgrt 7 wap3"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap3.zmd.fedex.com"
SYSTEMS["wgrt 7 wap4"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap4.zmd.fedex.com"
SYSTEMS["wgrt 7 wap5"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap5.zmd.fedex.com"
SYSTEMS["wgrt 7 wap6"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap6.zmd.fedex.com"
SYSTEMS["wgrt 7 wap7"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap7.zmd.fedex.com"
SYSTEMS["wgrt 7 wap8"]="-J $firewall_username@$firewall_host $username@wgrtweb-wap8.zmd.fedex.com"

# WRTT SYSTEMS
SYSTEMS["wrtt 1 s1"]="$username@wrttsbox1.idev.fedex.com"
SYSTEMS["wrtt 1 1"]="$username@wrttbase1.idev.fedex.com"
SYSTEMS["wrtt 2 1"]="$username@wrttdev1.idev.fedex.com"
SYSTEMS["wrtt 2 2"]="$username@wrttdev2.idev.fedex.com"
SYSTEMS["wrtt 3 cos1"]="$username@wrttdrt-cos1.idev.fedex.com"
SYSTEMS["wrtt 3 cos2"]="$username@wrttdrt-cos2.idev.fedex.com"
SYSTEMS["wrtt 3 wap1"]="$username@wrttdrt-wap1.idev.fedex.com"
SYSTEMS["wrtt 3 wap2"]="$username@wrttdrt-wap2.idev.fedex.com"
SYSTEMS["wrtt 4 cos1"]="$username@wrttstress-cos1.zmd.idev.fedex.com"
SYSTEMS["wrtt 4 cos2"]="$username@wrttstress-cos2.zmd.idev.fedex.com"
SYSTEMS["wrtt 4 wap1"]="$username@wrttstress-wap1.zmd.idev.fedex.com"
SYSTEMS["wrtt 4 wap2"]="$username@wrttstress-wap2.zmd.idev.fedex.com"
SYSTEMS["wrtt 5 1"]="$username@wrttbit1.idev.fedex.com"
SYSTEMS["wrtt 5 2"]="$username@wrttbit2.idev.fedex.com"
SYSTEMS["wrtt 6 cos1"]="$username@wrtttest-cos1.zmd.fedex.com"
SYSTEMS["wrtt 6 cos2"]="$username@wrtttest-cos2.zmd.fedex.com"
SYSTEMS["wrtt 6 wap1"]="$username@wrtttest-wap1.zmd.fedex.com"
SYSTEMS["wrtt 6 wap2"]="$username@wrtttest-wap2.zmd.fedex.com"
SYSTEMS["wrtt 6 wap2"]="$username@wrtttest-wap2.zmd.fedex.com"
SYSTEMS["wrtt 7 cos1"]="-J $firewall_username@$firewall_host $username@wrtt-cos1.zmd.fedex.com"
SYSTEMS["wrtt 7 cos2"]="-J $firewall_username@$firewall_host $username@wrtt-cos2.zmd.fedex.com"
SYSTEMS["wrtt 7 cos3"]="-J $firewall_username@$firewall_host $username@wrtt-cos3.zmd.fedex.com"
SYSTEMS["wrtt 7 cos4"]="-J $firewall_username@$firewall_host $username@wrtt-cos4.zmd.fedex.com"
SYSTEMS["wrtt 7 cos5"]="-J $firewall_username@$firewall_host $username@wrtt-cos5.zmd.fedex.com"
SYSTEMS["wrtt 7 wap1"]="-J $firewall_username@$firewall_host $username@wrtt-wap1.zmd.fedex.com"
SYSTEMS["wrtt 7 wap2"]="-J $firewall_username@$firewall_host $username@wrtt-wap2.zmd.fedex.com"
SYSTEMS["wrtt 7 wap3"]="-J $firewall_username@$firewall_host $username@wrtt-wap3.zmd.fedex.com"
SYSTEMS["wrtt 7 wap4"]="-J $firewall_username@$firewall_host $username@wrtt-wap4.zmd.fedex.com"
SYSTEMS["wrtt 7 wap5"]="-J $firewall_username@$firewall_host $username@wrtt-wap5.zmd.fedex.com"

# sag server
SYSTEMS["sag"]="$firewall_username@$firewall_host"

# personal homepage
SYSTEMS["stormlife"]="timsto26@www.stormlife.info"

# list all servers on 0 args
if [ "$#" -eq "0" ]; then
  for i in "${!SYSTEMS[@]}"; do
    printf "%-15s %s : %s\n" "$i" "${SYSTEMS[$i]}"
  done 
  exit
fi

if [ "$1" == "help" ]; then
  echo "usage: `basename $0` [app] [level] [server]"
  echo "example: `basename $0` wgrt 3 cos1"
  exit
fi

# login to remote host
ssh ${SYSTEMS[$@]}
